name: meeting-reminder

on:
  schedule:
    - cron:  '25 15 * * *'

jobs:
  meeting-reminder:
    name: meeting reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
        
    - name: meeting reminder
      run: 
        npm install
        node qyweixinbot.js
