name: meeting-reminder

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * 5'

jobs:
  meeting-reminder:
    name: meeting reminder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm install
    - run: npm install axios
    - run: node qyweixinbot.js
