name: meeting-reminder

on:
  schedule:
    - cron:  '35 10 * * *'
    - cron:  '45 10 * * *'

jobs:
  meeting-reminder:
    name: meeting reminder
    runs-on: ubuntu-latest
    steps:
    - name: meeting reminder
      run: node qyweixinbot.js
